### ISSUE TITLE
AniList API suddenly stopped working...

### ISSUE THREAD

**Issue by Ardrago19** [Soviena/kaa.si-cli#3]
**Version** 1.0.7

**Error:** 
```
FAILED TO CONNECT TO ANILIST!

Too Many request or anilist API is down!
pls wait a few minutes and try again
```

I have waited for days just to see if it was just the API which was offline or that I've sent too many requests, AniList does not have anywhere to check the status of the API.

**Comment by Soviena** [comment]
Is that happens when u try to sync your anime ?

**Comment by Ardrago19** [comment]
Sorry for not responding quickly I didn't check this github until now ;-;, ye suddenly this started happening to me whenever I try to sync my anime.

**Comment by Soviena** [comment]
Maybe it's Because timeout connecting to kaa.si, not anilist api. Happens to me sometime. Try using cloudflare warp and see if it fixes the problem.

**Comment by Ardrago19** [comment]
> Maybe it's Because timeout connecting to kaa.si, not anilist api. Happens to me sometime. Try using cloudflare warp and see if it fixes the problem.

I already do use cloudflare(1.1.1.1 in my DNS settings)

**Comment by Soviena** [comment]
Use the warp one, download from https://1.1.1.1/

 Either way, this problem occurs when you get timeout when requesting data from kaa.si

In the meantime, I'm still working in new faster and efficient request algorithm

**Comment by Ardrago19** [comment]
> Use the warp one, download from https://1.1.1.1/
> 
> Either way, this problem occurs when you get timeout when requesting data from kaa.si
> 
> In the meantime, I'm still working in new faster and efficient request algorithm

I have installed and ran cloudflare warp.

The output of 
`warp-cli status` 
is
`Status update: Connected`
`Success`

But I still do have the same error when I try to sync. anyways gl with working on the new algorithm, I'll just update my anilist manually for now.

**Comment by Soviena** [comment]
Sorry for this problem. Can you send me your anilist username for a reference

**Comment by Ardrago19** [comment]
> Sorry for this problem. Can you send me your anilist username for a reference

Sure, my anilist username is "Ardrago"

**Comment by Soviena** [comment]
Weird, but i can't find your username. Is your profile is private by any chance ? If so then the app cant read your watching list. Try changing your profile visibility to public. And after that delete kaasi.txt in your working directory or add key value `'username' : 'Ardrago'`

**Comment by Ardrago19** [comment]
> 

Oh damn, yep I've changed my privacy settings and I'll test it and lyk when I get home. Thanks!

**Comment by Ardrago19** [comment]
> > 
> 
> Oh damn, yep I've changed my privacy settings and I'll test it and lyk when I get home. Thanks!

It works now :D, didn't even have to change the kaasi or add a key value for the username. Thanks!
